services:
  - type: web
    name: chatbot-zoe-frontend
    buildCommand: "yarn install --immutable --check-cache && yarn build"
    startCommand: "yarn start"
    env:
      NODE_ENV: production
    buildEnvironment:
      - corepack: true
