services:
  - name: chatbot-zoe-frontend
    type: web
    env: static
    buildCommand: "corepack enable && yarn install --immutable && yarn build"
    staticPublishPath: "dist"
    envVars:
      - key: NODE_VERSION
        value: 18
